apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: users
  template: 
    metadata:
      labels:
        app: users
    spec:
      containers:
       - name: users
         image: yuvikadhiman25/kuber-network-app:latest
         env:
          - name: AUTH_ADDRESS
          # value: "10.101.60.86"  manual cluster IP
            value: "auth-service.default" 
            

            # value: localhost

      #  - name: auth
      #    image: yuvikadhiman25/kuber-auth-app:latest
       
        

